import './globals.css';
import Header from './_components/Header.jsx';
import Footer from './_components/Footer.jsx';
import { ClerkProvider } from '@clerk/nextjs';
import { lato } from './fonts/font';

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable}  antialiased bg-slate-50 text-slate-500 min-h-screen overflow-x-hidden`}
      >
        <ClerkProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </ClerkProvider>
      </body>
    </html>
  );
}
